### ISSUE TITLE
Support encryption at rest

### ISSUE THREAD

**Issue by andersharrisson-ess** [alvistack/ansible-collection-kubernetes#4]
It would be useful if the roles supports encryption at rest: https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

**Comment by hswong3i** [comment]
This looks interesting to me. I had some study on https://learn.hashicorp.com/vault/identity-access-management/vault-agent-k8s but seems vault couldn't act as such KMS provider for Kubernetes.

Beside above initial research I don't have any idea for implementing data encryption for Kubernetes yet. Could you share for more idea or information?

**Comment by aharrisson** [comment]
I have used the Hashicorp Vault Agent, but it's not straightforward and adds complexity to the applications. I think it's too much application space for your roles.
I guess that leaves two alternatives:
- A simple EncryptionConfiguration on the api-server
- KMS provider plugin
There are Vault KMS provider plugins, https://github.com/oracle/kubernetes-vault-kms-plugin, but I have never tried it and have no idea how well it works.

I think it would make more sense to use option 1. It's not the most secure solution, but it's simple and at least secures copies of etcd.

**Comment by hswong3i** [comment]
PR is welcome
