### ISSUE TITLE
Support for arm?

### ISSUE THREAD

**Issue by ccamacho** [alvistack/ansible-collection-kubernetes#8]
Hello,

Do you support arm?

**Comment by hswong3i** [comment]
With current limited man power and resource, arm support is not in roadmap, yet:
* My clients use amd64, for both bare metal, private cloud or public cloud
* All these Ansible Collection and Roles are tested with amd64 Vagrant + Libvirt (with my in-house Dell R620 x3 as GitLab Runner for CI)
* All these OBS repo (see https://build.opensuse.org/project/show/home:alvistack) are enabled with amd64 only. They are the base for above Ansible Roles.
* In case you would like to have a relatively stable arm support from Ubuntu / Fedora / openSUSE, most likely you will need the latest rolling release for now, e.g. Fedora Rawhide or openSUSE Tumbleweed (which are not daily data center production ready and focus)

Back to the 1st point: no paid production use case from client, no funding and resource for corresponding arm support.

P.S. contribution is welcome, but first of all we need to make our OBS repo support arm smoothly.

**Comment by ccamacho** [comment]
Hi, Im trying that but im hitting some issues, Ill close this and open another with the error im hitting, thanks!
